<a href="https://colab.research.google.com/github/arikaran007/detection/blob/main/plant_disease_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from zipfile import ZipFile
file_name='/content/drive/MyDrive/archive (4).zip'

with ZipFile(file_name,'r') as zip:
  zip.extractall()
  print('done')

done


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import models,layers,datasets
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [ ]:
IMAGE_SIZE=256
CHANNELS=3


In [ ]:
train_datagen=ImageDataGenerator(
    rescale=1.0/255,
    horizontal_flip=True,
    rotation_range=10

)

train_generator=train_datagen.flow_from_directory(
         '/content/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode='sparse'
         )

Found 70295 images belonging to 38 classes.


In [ ]:
validation_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True)


validation_generator=validation_datagen.flow_from_directory(
         '/content/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode='sparse'
         )

Found 17572 images belonging to 38 classes.


In [ ]:
count=0
for image_batch, label_batch in train_generator:
#     print(label_batch)
    print(image_batch[0])
    break

[[[0.72156864 0.6745098  0.68235296]
  [0.72156864 0.6745098  0.68235296]
  [0.72156864 0.6745098  0.68235296]
  ...
  [0.5694231  0.52236426 0.53805053]
  [0.5923152  0.5452563  0.5609426 ]
  [0.59607846 0.54901963 0.5647059 ]]

 [[0.7209414  0.6738826  0.68172574]
  [0.7210674  0.67400855 0.68185174]
  [0.7211934  0.67413455 0.6819777 ]
  ...
  [0.57005286 0.522994   0.53868026]
  [0.5930708  0.546012   0.56169826]
  [0.59607846 0.54901963 0.5647059 ]]

 [[0.7170219  0.66996306 0.6778062 ]
  [0.7171479  0.67008907 0.6779322 ]
  [0.7172738  0.67021495 0.6780581 ]
  ...
  [0.5706825  0.5236237  0.53931   ]
  [0.59382653 0.5467677  0.562454  ]
  [0.59607846 0.54901963 0.5647059 ]]

 ...

 [[0.505505   0.46236777 0.48589718]
  [0.5019608  0.45882356 0.48235297]
  [0.5023341  0.45919687 0.48272628]
  ...
  [0.2627451  0.22352943 0.21960786]
  [0.2627451  0.22352943 0.21960786]
  [0.2627451  0.22352943 0.21960786]]

 [[0.5053791  0.46224183 0.48577124]
  [0.5019608  0.45882356 0.48235297]


In [ ]:
for image_batch, label_batch in validation_generator:
    print(image_batch[0])
    break


[[[0.51121175 0.48768234 0.53474116]
  [0.59867424 0.5751448  0.62220365]
  [0.60511184 0.5815824  0.62864125]
  ...
  [0.5444585  0.5209291  0.5679879 ]
  [0.6035007  0.5799713  0.62703013]
  [0.61674213 0.5932127  0.64027154]]

 [[0.51393926 0.49040982 0.5374687 ]
  [0.58305484 0.55952543 0.60658425]
  [0.60670096 0.58317155 0.63023037]
  ...
  [0.6274943  0.60396487 0.6510237 ]
  [0.5900448  0.5665154  0.6135742 ]
  [0.5842059  0.5606765  0.60773534]]

 [[0.5327243  0.5091949  0.55625373]
  [0.5244134  0.500884   0.5479429 ]
  [0.610233   0.5867036  0.6337624 ]
  ...
  [0.6137866  0.59025717 0.637316  ]
  [0.55634224 0.53281283 0.57987165]
  [0.54653245 0.52300304 0.57006186]]

 ...

 [[0.6623942  0.64670795 0.7016099 ]
  [0.66110665 0.6454204  0.70032233]
  [0.65220976 0.6365235  0.69142544]
  ...
  [0.6983835  0.68269724 0.7375992 ]
  [0.7292061  0.7135198  0.76842177]
  [0.7384505  0.72276425 0.7776662 ]]

 [[0.6805679  0.66488165 0.7197836 ]
  [0.6788668  0.66318053 0.7180825 ]


In [ ]:
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
n_classes = 38

model = models.Sequential([
    layers.InputLayer(input_shape=input_shape),
    layers.Conv2D(32, kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64,  kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64,  kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation='softmax'),
])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 254, 254, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 127, 127, 32)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 125, 125, 64)      18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 62, 62, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 60, 60, 64)        36928     
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 30, 30, 64)       0

In [ ]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)


In [ ]:
history = model.fit(
    train_generator,
    batch_size=32,
    verbose=1,
    epochs=20,
)

Epoch 1/20
2197/2197 [==============================] - 1170s 532ms/step - loss: 1.4748 - accuracy: 0.5623
Epoch 2/20
2197/2197 [==============================] - 1126s 512ms/step - loss: 0.5734 - accuracy: 0.8154
Epoch 3/20
 652/2197 [=======>......................] - ETA: 12:32 - loss: 0.4425 - accuracy: 0.8560